// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Pharmatechnik.Language.Gd.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GdLanguagePackageGuidString = "ecad3e41-42ea-49c5-be56-4865b09c0fcd";
        public static Guid GdLanguagePackageGuid = new Guid(GdLanguagePackageGuidString);

        public const string GdLanguagePackageCmdSetGuidString = "a6c3ace3-0816-4c80-943d-d043c438deb8";
        public static Guid GdLanguagePackageCmdSetGuid = new Guid(GdLanguagePackageCmdSetGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowGdOutlineWindow = 0x0100;
    }
}